name: SCUM Update Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get SCUM news
        run: |
          curl -s https://store.steampowered.com/feeds/news/app/513710/ > feed.xml
          TITLE=$(grep -oPm2 "(?<=<title>).*?(?=</title>)" feed.xml | sed -n '2p')

          echo "TITLE=$TITLE" >> $GITHUB_ENV

      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"📢 SCUM Update: $TITLE\"}" \
     https://discord.com/api/webhooks/1499484638878498996/uMs11agj7w4f-ztTFUKFZ5Tr3DJ6d404ljOoNram4wG-GJtl8610TJJKlEuX49l6wQ-v
